
INSERT INTO cdus (codigo, tema) VALUES
('002', 'Documentação. Documentos em geral'),
('002/42', 'Documentação. Documentos em geral. CD-ROM'),
('002/49', 'Documentação. Documentos em geral. E-BOOK'),
('003', 'Escrita. Sintaxe e Semântica em geral. Sinais Gráficos'),
('003/44', 'Escrita. Sintaxe e Semântica em geral. Sinais Gráficos. CASSETE'),
('003.24', 'Caracteres Braille (Técnica do Braille)'),
('01', 'Bibliografia. Catálogos. Lista de Livros'),
('01/42', 'Bibliografia. Catálogos. Lista de Livros. CD-ROM'),
('01/49', 'Bibliografia. Catálogos. Lista de Livros. E-BOOK'),
('02', 'Biblioteconomia. Classificação. Indexação. Bibliotecas. Leitura'),
('02/47', 'Biblioteconomia. Classificação. Indexação. Bibliotecas. Leitura. PDF'),
('03', 'Obras de referência. Enciclopédias. Dicionários'),
('03/42', 'Obras de referência. Enciclopédias. Dicionários. CD-ROM'),
('03/43', 'Obras de referência. Enciclopédias. Dicionários. DISQUETE'),
('03/46', 'Obras de referência. Enciclopédias. Dicionários. DVD-ROM'),
('03/49', 'Obras de referência. Enciclopédias. Dicionários. E-BOOK'),
('05', 'Guias profissionais. Agendas'),
('05/42', 'Guias profissionais. Agendas. CD-ROM'),
('05/47', 'Guias profissionais. Agendas. PDF'),
('058', 'Anuários. Anais. Outras publicações anuais'),
('059', 'Calendários. Almanaques'),
('06', 'Museografia. Museologia. Catálogos de exposições'),
('06/41', 'Museografia. Museologia. Catálogos de exposições. VÍDEO CASSETE'),
('06/42', 'Museografia. Museologia. Catálogos de exposições. CD-ROM'),
('061', 'Escutismo. Organizações de Juventude'),
('07', 'Jornalismo'),
('087.7', 'Publicações oficiais. Livros brancos'),
('09', 'Ex-Libris. Livros raros. Manuscritos. Bibliofilia'),
('09/42', 'Ex-Libris. Livros raros. Manuscritos. Bibliofilia. CD-ROM'),
('10', 'Filosofia em geral'),
('11', 'Metafísica'),
('13', 'Filosofia do espírito'),
('133', 'Ocultismo. Astrologia. Parapsicologia'),
('14', 'Sistemas filosóficos'),
('141.33', 'Esoterismo'),
('141.33/42', 'Esoterismo. CD-ROM'),
('159.9', 'Psicologia'),
('159.964', 'Psicanálise'),
('16', 'Lógica. Teoria do conhecimento'),
('17', 'Moral. Ética'),
('17/47', 'Moral. Ética. PDF'),
('19', 'História da filosofia'),
('22', 'Bíblia'),
('22/42', 'Bíblia. CD-ROM'),
('23', 'Teologia dogmática'),
('24', 'Teologia moral. Prática religiosa'),
('24/42', 'Teologia moral. Prática religiosa. CD-ROM'),
('247', 'Mobiliário e Decoração de Igrejas'),
('25', 'Teologia pastoral'),
('26', 'Igreja cristã em geral'),
('27', 'História da Igreja cristã'),
('28', 'Igrejas. Seitas'),
('282', 'Igreja católica'),
('283', 'Igreja protestante'),
('285/288', 'Outras Igrejas cristãs'),
('29', 'Ciência religiosa em geral e em particular'),
('291', 'Ciência e história comparada das religiões'),
('292', 'Religião dos gregos e dos romanos antigos. Mitologia'),
('294', 'Religião dos Hindus'),
('296', 'Religião judaica'),
('297', 'Islamismo. Maometismo'),
('299', 'Outras religiões não cristãs'),
('299.5', 'Religiões dos povos asiáticos orientais (confucionismo, taoísmo, etc.)'),
('301', 'Sociologia'),
('301/42', 'Sociologia. CD-ROM'),
('31', 'Estatística. Demografia'),
('31/42', 'Estatística. Demografia. CD-ROM'),
('32', 'Política'),
('324', 'Eleições. Plebiscitos'),
('325', 'Descolonização. Administração colonial'),
('326', 'Escravatura, luta contra a escravatura'),
('327', 'Relações políticas internacionais'),
('329', 'Partidos e movimentos políticos'),
('33', 'Economia'),
('33/42', 'Economia. CD-ROM'),
('33/43', 'Economia. DISQUETE'),
('33.34', 'Direito económico'),
('331', 'Trabalho. Emprego. Economia do Trabalho. Organização do Trabalho'),
('331/42', 'Trabalho. Emprego. Economia do Trabalho. Organização do Trabalho. CD-ROM'),
('331/47', 'Trabalho. Emprego. Economia do Trabalho. Organização do Trabalho. PDF'),
('331/49', 'Trabalho. Emprego. Economia do Trabalho. Organização do Trabalho. E-BOOK'),
('336', 'Finanças'),
('336.4', 'Direito alfandegário  3'),
('339.5', 'Direito dos consumidores'),
('34', 'Direito. Jurisprudência'),
('34/42', 'Direito. Jurisprudência. CD-ROM'),
('34/46', 'Direito. Jurisprudência. DVD-ROM'),
('34/49', 'Direito. Jurisprudência. E-BOOK'),
('340', 'Direito em geral'),
('340.11', 'Teoria geral do direito. Introdução ao direito'),
('340.12', 'Filosofia do direito'),
('340.13', 'Fontes do direito'),
('340.5', 'Direito comparado'),
('340.6', 'Medicina legal. Ciências auxiliares do direito'),
('341', 'Direito internacional'),
('341.1', 'Direito internacional público'),
('341.17', 'Conselho da Europa'),
('341.178', 'Direito comunitário'),
('341.18', 'Comunidade Económica Europeia'),
('341.24', 'Tratados Internacionais. Convenções Internacionais'),
('341.3', 'Direito de Guerra. Relações de direito internacional em período de  guerra'),
('341.4', 'Direito penal internacional'),
('341.5', 'Direito internacional privado'),
('341.6', 'Arbitragem internacional'),
('341.7', 'Direito diplomático'),
('341.8', 'Direito consular'),
('342', 'Direito público. Direito constitucional'),
('342.4', 'Constituições'),
('342.53', 'Parlamento. Direito parlamentar'),
('342.7', 'Direitos do Homem'),
('342.8', 'Direito eleitoral. Sistemas eleitorais'),
('343.1', 'Direito processual penal'),
('343.2', 'Direito penal. Código da estrada'),
('343.2/42', 'Direito penal. Código da estrada. CD-ROM'),
('343.2/46', 'Direito penal. Código da estrada. DVD-ROM'),
('344', 'Direito penal especial'),
('347', 'Direito civil'),
('347.1', 'Teoria geral do direito civil'),
('347.2', 'Direito das coisas'),
('347.4', 'Direito das obrigações. Contratos'),
('347.6', 'Direito da família. Direito das sucessões'),
('347.7', 'Direito comercial'),
('347.72', 'Sociedades comerciais'),
('347.77', 'Propriedade Industrial'),
('347.78', 'Propriedade literária e artística. Direitos de autor'),
('347.79', 'Direito marítimo'),
('347.8', 'Direito aéreo'),
('347.91', 'Direito processual civil'),
('347.96', 'Organização judiciária. Tribunais. Magistrados. Ministério Público. Advogados'),
('348', 'Direito canónico'),
('349', 'Direito do trabalho'),
('349/47', 'Direito do trabalho. PDF'),
('35', 'Administração pública. Direito administrativo'),
('35.08', 'Função Pública. Funcionalismo Público'),
('352', 'Administração local'),
('353', 'Administração regional'),
('354', 'Administração central'),
('355/35', 'Arte militar. Ciências militares. Defesa nacional. Exército. Marinha. Ensino da guerra.'),
('36', 'Assistência. Segurança social'),
('37', 'Educação. Ensino. Pedagogia'),
('37/41', 'Educação. Ensino. Pedagogia. VÍDEO CASSETE'),
('37/42', 'Educação. Ensino. Pedagogia. CD-ROM'),
('37/43', 'Educação. Ensino. Pedagogia. DISQUETE'),
('37/44', 'Educação. Ensino. Pedagogia. CASSETE'),
('37/46', 'Educação. Ensino. Pedagogia. DVD-ROM'),
('37/49', 'Educação. Ensino. Pedagogia. E-BOOK'),
('371.32', 'Manuais Escolares'),
('371.32/42', 'Manuais Escolares. CD-ROM'),
('371.32/43', 'Manuais Escolares. DISQUETE'),
('371.32/44', 'Manuais Escolares. CASSETE'),
('371.32/45', 'Manuais Escolares. CD-AUDIO'),
('374.7', 'Educação de Adultos'),
('374.7/42', 'Educação de Adultos. CD-ROM'),
('374.7/49', 'Educação de Adultos. E-BOOK'),
('375', 'Livros de apoio ao manual escolar'),
('375/42', 'Livros de apoio ao manual escolar. CD-ROM'),
('375/43', 'Livros de apoio ao manual escolar. DISQUETE'),
('375/44', 'Livros de apoio ao manual escolar. CASSETE'),
('375/45', 'Livros de apoio ao manual escolar. CD-AUDIO'),
('375/46', 'Livros de apoio ao manual escolar. DVD-ROM'),
('376', 'Educação de Deficientes.'),
('377/37', 'Ensino Técnico Profissional. Ensino Superior. Universidades'),
('377/37/42', 'Ensino Técnico Profissional. Ensino Superior. Universidades. CD-ROM'),
('38', 'Comércio'),
('380.8', 'Turismo (organização), intérpretes e guias, roteiros, cartas turísticas, guias impressos'),
('380.8/42', 'Turismo (organização), intérpretes e guias, roteiros, cartas turísticas, guias impressos. CD-ROM'),
('381', 'Comércio Interno'),
('382', 'Comércio Externo'),
('383/38', 'Comunicações. Transporte'),
('389', 'Pesos e Medidas. Normalização'),
('39', 'Etnografia. Folclore, Costumes. Usos e costumes. Feminismo'),
('39/40', 'Etnografia. Folclore, Costumes. Usos e costumes. Feminismo. AUDIOLIVRO'),
('39/41', 'Etnografia. Folclore, Costumes. Usos e costumes. Feminismo. VÍDEO CASSETE'),
('39/44', 'Etnografia. Folclore, Costumes. Usos e costumes. Feminismo. CASSETE'),
('391', 'Moda. Vestuário'),
('50', 'Ciências exactas e puras em geral'),
('51', 'Matemática'),
('51/43', 'Matemática. Disquete'),
('52', 'Astronomia. Geodésia'),
('527', 'Astronomia Náutica e Aeronáutica. Navegação'),
('53', 'Física'),
('531', 'Mecânica dos sólidos, corpos rígidos'),
('532', 'Mecânica dos fluídos. Hidráulica'),
('533', 'Teoria do gás. Aerodinâmica  5'),
('534', 'Vibrações. Acústica'),
('534/47', 'Vibrações. Acústica. PDF'),
('535', 'Óptica. Luz'),
('536', 'Calor'),
('537', 'Electricidade'),
('538', 'Magnetismo'),
('539', 'Física nuclear, atómica e molecular'),
('54', 'Química'),
('55', 'Ciências geológicas e geofísicas'),
('55/42', 'Ciências geológicas e geofísicas. CD-ROM'),
('551.1', 'Geologia geral'),
('551.1/42', 'Geologia geral. CD-ROM'),
('551.5', 'Meteorologia. Climatologia'),
('551.7', 'Estatigrafia. Geologia histórica'),
('552', 'Petrologia. Litologia. Petrografia'),
('553', 'Geologia económica. Mineralogia'),
('56', 'Paleontologia. Fósseis'),
('57', 'Ciências biológicas'),
('572', 'Antropologia'),
('574/57', 'Biologia geral'),
('575', 'Hereditariedade e evolução dos seres orgânicos'),
('576', 'Biofísica. Bioquímica. Biologia molecular da célula. Parasitologia'),
('577.4', 'Ecologia'),
('577.4/42', 'Ecologia. CD-ROM'),
('577.4/49', 'Ecologia. E-BOOK'),
('58', 'Botânica'),
('59', 'Zoologia'),
('59/42', 'Zoologia. CD-ROM'),
('61', 'Medicina'),
('61/42', 'Medicina. CD-ROM'),
('611', 'Anatomia'),
('612', 'Fisiologia'),
('613', 'Puericultura. Planeamento Familiar. Vida sexual. Violência doméstica'),
('614', 'Saúde pública. Socorrismo. Vacinas. Bombeiros'),
('614/42', 'Saúde pública. Socorrismo. Vacinas. Bombeiros. CD-ROM'),
('615', 'Terapêutica. Farmacologia. Toxicologia'),
('615.19', 'Saúde natural. Medicinas alternativas'),
('615.19/42', 'Saúde natural. Medicinas alternativas. CD-ROM'),
('616', 'Patologia. Medicina clínica'),
('616.08', 'Enfermagem'),
('616.31', 'Odontologia'),
('617', 'Cirurgia. Ortopedia. Oftalmologia'),
('618', 'Ginecologia. Obstetrícia'),
('619', 'Medicina veterinária'),
('62', 'Engenharia'),
('62/42', 'Engenharia. CD-ROM'),
('620.9', 'Energia em geral'),
('621', 'Mecânica em geral. Engenharia electrotécnica. Tecnologia nuclear'),
('621.3', 'Electrotecnia. Electrónica'),
('621.3/47', 'Electrotecnia. Electrónica. PDF  6'),
('621.39', 'Transmissão de imagens. Televisão. Vídeo'),
('621.39/42', 'Transmissão de imagens. Televisão. Vídeo. CD-ROM'),
('622', 'Engenharia mineira'),
('623', 'Engenharia militar e naval'),
('624', 'Engenharia civil'),
('625', 'Engenharia dos transportes'),
('626', 'Engenharia hidráulica, canais, drenagem'),
('627', 'Engenharia hidráulica nos rios e no mar, barragens, portos'),
('628', 'Engenharia sanitária'),
('629', 'Técnica dos meios de transporte'),
('629/42', 'Técnica dos meios de transporte. CD-ROM'),
('629.11', 'Veículos terrestres'),
('629.11/42', 'Veículos terrestres. CD-ROM'),
('629.12', 'Meios de transporte sobre água. Navios e barcos'),
('629.13', 'Aeronáutica. Construções aeronáuticas'),
('629.19', 'Astronáutica'),
('63', 'Agricultura. Silvicultura'),
('631/63', 'Agronomia geral. Doença das plantas. Culturas herbáceas. Arboricultura. Florestas. Pomares. Horticultura. Jardins. Floricultura.'),
('631/63/41', 'Agronomia geral. Doença das plantas. Culturas herbáceas. Arboricultura. Florestas. Pomares. Horticultura. Jardins. Floricultura. VÍDEO CASSETE'),
('631/63/42', 'Agronomia geral. Doença das plantas. Culturas herbáceas. Arboricultura. Florestas. Pomares. Horticultura. Jardins. Floricultura. CD-ROM'),
('636/63', 'Criação de animais e seus produtos.'),
('639', 'Caça. Pesca. Piscicultura.'),
('64', 'Economia doméstica'),
('64.024', 'Hotelaria'),
('641.64', 'Alimentação. Preparação de alimentos. Refeições.'),
('641.64/42', 'Alimentação. Preparação de alimentos. Refeições. CD-ROM'),
('641.64/49', 'Alimentação. Preparação de alimentos. Refeições. E-BOOK'),
('646', 'Vida prática.'),
('65', 'Gestão e organização da indústria e do comércio.'),
('65/40', 'Gestão e organização da indústria e do comércio. AUDIOLIVRO'),
('65/42', 'Gestão e organização da indústria e do comércio. CD-ROM'),
('65/43', 'Gestão e organização da indústria e do comércio. DISQUETE'),
('654', 'Telecomunicações'),
('655', 'Indústria do livro'),
('656', 'Transportes. Correios (organização e gestão)'),
('656.83', 'Filatelia'),
('657', 'Contabilidade'),
('658', 'Organização de empresas. Técnicas do comércio'),
('658/42', 'Organização de empresas. Técnicas do comércio. CD-ROM'),
('658/47', 'Organização de empresas. Técnicas do comércio. PDF'),
('658.82', 'Marketing'),
('659.1', 'Publicidade'),
('659.2', 'Informações. Agências de informação'),
('659.4', 'Relações públicas'),
('66', 'Indústrias químicas. Técnicas químicas. Metalurgia'),
('66/47', 'Indústrias químicas. Técnicas químicas. Metalurgia. PDF'),
('663', 'Enologia'),
('668.5', 'Perfumaria. Cosmética. Beleza'),
('67/68', 'Indústrias e metais diversos. Tecnologia mecânica'),
('67/68/42', 'Indústrias e metais diversos. Tecnologia mecânica. CD-ROM'),
('681.3', 'Informática  7'),
('681.3/42', 'Informática. CD-ROM'),
('69', 'Indústria da construção'),
('69/42', 'Indústria da construção. CD-ROM'),
('69/47', 'Indústria da construção. PDF'),
('7.0', 'Arte em geral. Teoria da Arte. Filosofia da Arte'),
('7.0/42', 'Arte em geral. Teoria da Arte. Filosofia da Arte. CD-ROM'),
('7.01', 'Estética'),
('7.03', 'Estilos e influências'),
('7.072', 'História da arte'),
('71', 'Urbanismo. Ordenamento do território. Arquitectura de jardins'),
('71/42', 'Urbanismo. Ordenamento do território. Arquitectura de jardins. CD-ROM'),
('72', 'Arquitectura'),
('72/42', 'Arquitectura. CD-ROM'),
('72/46', 'Arquitectura. DVD-ROM'),
('73', 'Escultura'),
('736', 'Sigilografia'),
('737', 'Numismática'),
('738', 'Cerâmica artística'),
('738.1', 'Porcelana'),
('738.2', 'Vidro'),
('738.5', 'Mosaico'),
('738.8', 'Azulejo'),
('738.8/42', 'Azulejo. CD-ROM'),
('739', 'Arte do metal. Joalharia. Ourivesaria'),
('74', 'Desenho'),
('745', 'Artes decorativas. Trabalhos manuais. Artesanato'),
('747', 'Decoração de interiores'),
('749', 'Mobiliário'),
('75', 'Pintura'),
('76', 'Artes gráficas. Gravuras. Litografia'),
('77', 'Fotografia'),
('77/42', 'Fotografia. CD-ROM'),
('778.5', 'Cinematografia'),
('78', 'Música'),
('78/42', 'Música. CD-ROM'),
('78/44', 'Música. Cassete'),
('79', 'Divertimentos, passatempos, jogos, desportos'),
('79/42', 'Divertimentos, passatempos, jogos, desportos. CD-ROM'),
('791', 'Divertimentos públicos e espectáculos públicos'),
('792', 'Teatro'),
('793', 'Dança'),
('794', 'Jogos de sociedade. Jogos de memória'),
('796', 'Jogos e desportos ao ar livre. Desportos atléticos'),
('796/41', 'Jogos e desportos ao ar livre. Desportos atléticos. VÍDEO CASSETE'),
('796/42', 'Jogos e desportos ao ar livre. Desportos atléticos. CD-ROM'),
('796.7', 'Automobilismo. Motociclismo. Desporto automóvel'),
('797', 'Desportos sobre e na água. Desportos no ar'),
('798', 'Desportos a cavalo. Hipismo. Equitação'),
('799', 'Pesca. Caça. Tiro'),
('80', 'Linguística. Filologia'),
('80/42', 'Linguística. Filologia. CD-ROM'),
('80/43', 'Linguística. Filologia. DISQUETE'),
('82', 'Literatura em geral'),
('82/42', 'Literatura em geral. CD-ROM'),
('82.091', 'História da literatura'),
('82.091/42', 'História da literatura. CD-ROM'),
('82.091/46', 'História da literatura. DVD-ROM'),
('82-1', 'Poesia'),
('82-1/47', 'Poesia. PDF'),
('82-1/49', 'Poesia. E-BOOK'),
('82-2', 'Teatro'),
('82-3', 'Romance. Novela. Conto. Histórias'),
('82-3/40', 'Romance. Novela. Conto. Histórias. AUDIOLIVRO'),
('82-3/41', 'Romance. Novela. Conto. Histórias. VÍDEO CASSETE'),
('82-3/47', 'Romance. Novela. Conto. Histórias. PDF'),
('82-3/49', 'Romance. Novela. Conto. Histórias. E-BOOK'),
('82-31', 'Literatura de espionagem'),
('82-311', 'Ficção científica'),
('82-311/49', 'Ficção científica. E-BOOK'),
('82-312', 'Literatura policial'),
('82-4', 'Ensaios'),
('82-4/42', 'Ensaios. CD-ROM'),
('82-4/47', 'Ensaios. PDF'),
('82-4/49', 'Ensaios. E-BOOK'),
('82-5', 'Discursos. Eloquência'),
('82-6', 'Epístolas. Cartas'),
('82-7', 'Humor. Sátira. Paródia'),
('82-7/42', 'Humor. Sátira. Paródia. CD-ROM'),
('82-8', 'Poligrafia. Miscelâneas. Extractos. Antologia'),
('82-9', 'Outras formas literárias'),
('82-90', 'B.D. - Adultos'),
('82-91', 'B.D. - Crianças e Jovens'),
('82-92', 'Livros para crianças até aos 6 anos'),
('82-92/42', 'Livros para crianças até aos 6 anos. CD-ROM'),
('82-92/44', 'Livros para crianças até aos 6 anos. VÍDEO CASSETE'),
('82-93', 'Literatura Infantil e Juvenil'),
('82-94', 'Memórias. História como género literário. Crónicas'),
('908', 'Monografias regionais'),
('908/42', 'Monografias regionais. CD-ROM'),
('91', 'Geografia'),
('91/42', 'Geografia. CD-ROM'),
('91/47', 'Geografia. PDF'),
('912', 'Cartas. Mapas. Plantas. Atlas. Globos'),
('912/42', 'Cartas. Mapas. Plantas. Atlas. Globos. CD-ROM'),
('92', 'Biografias. Autobiografias. Fotobiografias'),
('929', 'Genealogia. Heráldica  9'),
('929/42', 'Genealogia. Heráldica. CD-ROM'),
('93', 'História'),
('93/42', 'História. CD-ROM'),
('930', 'Ciência histórica (teoria geral da história). Ciências auxiliares da história (diplomática, cronologia, arquivística, epigrafia, paleografia)'),
('930/42', 'Ciência histórica (teoria geral da história). Ciências auxiliares da história (diplomática, cronologia, arquivística, epigrafia, paleografia). CD-ROM'),
('930.26', 'Arqueologia'),
('930.26/41', 'Arqueologia. VÍDEO CASSETE'),
('930.26/42', 'Arqueologia. CD-ROM'),
('931', 'História antiga'),
('94', 'História da Idade Média e História Moderna em geral'),
('940', 'História da Europa'),
('946.9', 'História de Portugal'),
('946.9/42', 'História de Portugal. CD-ROM'),
('946.99', 'História de Portugal no Ultramar'),
('950', 'História da Ásia'),
('951.23', 'História de Macau'),
('960', 'História de África'),
('966.57', 'História da Guiné-Bissau'),
('966.58', 'História de Cabo Verde'),
('966.99', 'História de S. Tomé e Príncipe'),
('967.3', 'História de Angola'),
('967.9', 'História de Moçambique'),
('967.9/42', 'História de Moçambique. CD-ROM'),
('970', 'História da América do Norte'),
('980', 'História da América do Sul'),
('981', 'História do Brasil'),
('992.35', 'História de Timor');
